// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trucking.Context;

#nullable disable

namespace Trucking.Migrations
{
    [DbContext(typeof(TruckContext))]
    partial class TruckContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Trucking.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destiny")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<int>("TripStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Viaje de ...",
                            Destiny = "CABA, Buenos Aires",
                            Source = "Rosario, Santa Fe",
                            TripStatus = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Viaje de ...",
                            Destiny = "Bariloche, Rio Negro",
                            Source = "Arroyo Seco, Buenos Aires",
                            TripStatus = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Viaje de ...",
                            Destiny = "Carlos Paz, Cordoba",
                            Source = "Rosario, Santa Fe",
                            TripStatus = 2
                        });
                });

            modelBuilder.Entity("Trucking.Entities.Trucker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompleteName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TruckerType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Truckers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompleteName = "Juan Gomez",
                            TruckerType = "Carga Seca"
                        },
                        new
                        {
                            Id = 2,
                            CompleteName = "Martin Suarez",
                            TruckerType = "Autos"
                        },
                        new
                        {
                            Id = 3,
                            CompleteName = "Agustin Ramirez",
                            TruckerType = "Ganaderia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
